services:
  db:
    image: mysql:8.0
    container_name: linguaflash-mysql
    environment:
      MYSQL_DATABASE: linguaflash
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
        - db_data:/var/lib/mysql
volumes:
    db_data: {}
