services:
  db:
    image: mysql:8.0
    container_name: linguaflash-mysql
    environment:
      MYSQL_DATABASE: linguaflash
      MYSQL_USER: root
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
volumes:
    db_data: {}
